### ISSUE TITLE
Re-activate EtcdDBTest testPutSomethingMoreComplexForSubTreeIntoDSReadItBackAndDelete

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-etcd#7]
while working on #4 I had to `@Ignore` the  `testPutSomethingMoreComplexForSubTreeIntoDSReadItBackAndDelete` in `EtcdDBTest` (all other tests passed) - the goal of this issue is to re-activate it and fix the problem:

```
java.lang.IllegalArgumentException: Node (urn:opendaylight:params:xml:ns:yang:mdsal:test:binding?revision=2014-07-01)nested-list[{(urn:opendaylight:params:xml:ns:yang:mdsal:test:binding?revision=2014-07-01)name=nested1}] is missing mandatory descendant /(urn:opendaylight:params:xml:ns:yang:mdsal:test:binding?revision=2014-07-01)type
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.MandatoryLeafEnforcer$Strict.enforceOnData(MandatoryLeafEnforcer.java:43)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.MandatoryLeafEnforcer.enforceOnTreeNode(MandatoryLeafEnforcer.java:58)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.ListEntryModificationStrategy.applyWrite(ListEntryModificationStrategy.java:49)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.SchemaAwareApplyOperation.apply(SchemaAwareApplyOperation.java:228)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.ModifiedNode.seal(ModifiedNode.java:279)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.AbstractReadyIterator.process(AbstractReadyIterator.java:57)
	at org.opendaylight.yangtools.yang.data.impl.schema.tree.InMemoryDataTreeModification.ready(InMemoryDataTreeModification.java:295)
	at org.opendaylight.etcd.ds.impl.EtcdDataStore.apply(EtcdDataStore.java:188)
	at org.opendaylight.etcd.ds.impl.EtcdDataStore.initialLoad(EtcdDataStore.java:181)
	at org.opendaylight.etcd.ds.impl.EtcdDataStore.init(EtcdDataStore.java:158)
	at org.opendaylight.etcd.ds.impl.EtcdDOMDataBrokerProvider.init(EtcdDOMDataBrokerProvider.java:92)
	at org.opendaylight.etcd.testutils.TestEtcdDataBrokerProvider.<init>(TestEtcdDataBrokerProvider.java:63)
	at org.opendaylight.etcd.testutils.test.EtcdDBTest.recreateFreshDataBrokerClient(EtcdDBTest.java:114)
	at org.opendaylight.etcd.testutils.test.EtcdDBTest.testPutSomethingMoreComplexForSubTreeIntoDSReadItBackAndDelete(EtcdDBTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.opendaylight.infrautils.testutils.LogRule$1.evaluate(LogRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by vorburger** [comment]
This was (only) on the bertrandlow-PR-5-with-more-fixes branch which I abandoned, forget about this.
